### ISSUE TITLE
Usage with Blueprints

### ISSUE THREAD

**Issue by morr0350** [lixxu/sanic-jinja2#6]
How would I pass the configured SanicJinja2 instance to my blueprints?   I see the instance adds a reference to itself to app.extensions, but I'm unsure how to access it outside of the file where the SanicJinja2 instance is created without getting a circular import.

**Comment by lixxu** [comment]
register the blueprints at the end

**Comment by lixxu** [comment]
simple example:
```python

from sanic import Sanic
from sanic_jinja2 import SanicJinja2
app = Sanic()
jinja = SanicJinja2(app)

# other codes
# ...

# register the blueprints at the end
from a_blueprint import bp

app.blueprint(bp)
```
```python
# a_blueprint.py

from sanic import Blueprint
from myapp import jinja

bp = Blueprint('my_blueprint')

@bp.route('/')
async def bp_root(request):
    return jinja.render('index.html', request)

```

**Comment by morr0350** [comment]
I think that's what I'm doing?: 

**hello.py**
```
from sanic import Sanic
from sanic.response import json
from sanic_session import InMemorySessionInterface
from sanic_jinja2 import SanicJinja2

app = Sanic(__name__)
jinja = SanicJinja2(app)
session = InMemorySessionInterface(cookie_name=app.name, prefix=app.name)

@app.middleware('request')
async def add_session_to_request(request):
        await session.open(request)

@app.middleware('response')
async def save_session(request, response):
        await session.save(request, response)

@app.route("/")
async def test(request):
        return json({"hello": "world"})

# register Blueprints
from api_v1 import api_v1
app.blueprint(api_v1, url_prefix='v1')

if __name__ == "__main__":
        app.run(host="0.0.0.0", port=8000)
```

**api_v1.py**
```
from sanic.response import text
from sanic import Blueprint
from hello import jinja

api_v1 = Blueprint('v1', url_prefix='/v1')
@api_v1.route('/')
async def api_v1_root(request):
        return await jinja.render_async("api_v1_home.html", request, message='Welcome to API V1')

```

This results in:
Traceback (most recent call last):
  File "hello.py", line 23, in <module>
    from api_v1 import api_v1
  File "/home/.../test/api_v1.py", line 3, in <module>
    from hello import jinja
  File "/home/.../test/hello.py", line 23, in <module>
    from api_v1 import api_v1
ImportError: cannot import name 'api_v1'

I think this is a probably circular import error?

**Comment by morr0350** [comment]
I fixed it by moving the circular import out of the module global namespace in api_v1.py:

**hello.py**
```
from sanic import Sanic
from sanic.response import json
from sanic_session import InMemorySessionInterface
from sanic_jinja2 import SanicJinja2

app = Sanic(__name__)
jinja = SanicJinja2(app, enable_async=True)
session = InMemorySessionInterface(cookie_name=app.name, prefix=app.name)

@app.middleware('request')
async def add_session_to_request(request):
        await session.open(request)

@app.middleware('response')
async def save_session(request, response):
        await session.save(request, response)

@app.route("/")
async def test(request):
        return json({"hello": "world"})

# register Blueprints
import api_v1
app.blueprint(api_v1.api_v1, url_prefix='v1')

if __name__ == "__main__":
        app.run(host="0.0.0.0", port=8000)
```

**api_v1.py**
```
from sanic.response import text
from sanic import Blueprint

api_v1 = Blueprint('v1', url_prefix='/v1')

@api_v1.route('/')
async def api_v1_root(request):
        from hello import jinja
        return await jinja.render("api_v1_home.html", request, message='Welcome to API V1')
```

Thanks!

**Comment by lixxu** [comment]
it's not circular import error. it's package or module import error. if you want to enable async, pass `enable_async=True`to SanicJinja2() and per jinja2 doc, async is only for python3.6+

**Comment by gugadev** [comment]
@lixxu I have Python 3.6 and the problem still here. Are you sure that isn't a circular import error?

**Comment by lixxu** [comment]
circular import error will show different error. You can move register blueprints lines after jinja setup line to see the circular import error.
